### ISSUE TITLE
queue:worker

### ISSUE THREAD

**Issue by 2bj** [fondbot/framework#42]
А почему `queue:worker` (`beanstalkd`) после выполнения одного job'а сразу выходит из loop'a?

**Comment by vyuldashev** [comment]
Странно, он должен продолжать работу, проверю.

**Comment by 2bj** [comment]
`Ubuntu 16.04 LTS`, `PHP 7.1.5`, `beanstalkd 1.10`

**Comment by 2bj** [comment]
А если явно указать `--jobs`, то держится до истечения счетчика:
```bash
./bin/toolbelt queue:worker -j 10
```

**Comment by vyuldashev** [comment]
Исправил. ```composer update``` подтянет версию v1.0.3 и все должно заработать как надо.

**Comment by 2bj** [comment]
👍
